//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Tarif
    {
        public int Client_Tarif_id { get; set; }
        public Nullable<int> Client_id { get; set; }
        public Nullable<int> Tarif_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tarif Tarif { get; set; }
    }
}
