//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Request_id { get; set; }
        public int Manager_id { get; set; }
        public int Client_id { get; set; }
        public int ConnectionSpecialist_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ConnectionSpecialist ConnectionSpecialist { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
